version: '3.8'

networks:
  railway-network:
    driver: bridge
    ipam:
      config:
        - subnet: 191.168.1.0/24
    driver_opts:
      com.docker.network.driver.mtu: 8999
      com.docker.network.bridge.enable_icc: "true"
      com.docker.network.bridge.enable_ip_masquerade: "true"


services:
  fn:
    build:
      context: ./FN
      dockerfile: Dockerfile
    image: react-docker-app:latest
    container_name: react-container
    networks:
      railway-network:
        # ipv4_address: 192.168.1.10
    dns_opt:
      - use-vc
    sysctls:
      - net.core.somaxconn=1024
      - net.ipv4.tcp_max_syn_backlog=1024
      - net.ipv4.ip_local_port_range=1024 65535
    volumes:
      - /tmp/nginx/client-body:/var/lib/nginx/client-body
      - /upload:/workspace
    environment:
      - NODE_ENV=production
      - REACT_APP_API_URL=/bn
      - NGINX_MAX_UPLOAD_SIZE=10G
      - NGINX_PROXY_TIMEOUT=600
      - NGINX_CONNECT_TIMEOUT=600
      - NODE_OPTIONS=--max-old-space-size=2048
      - VIRTUAL_HOST=exam-all.duckdns.org
      - LETSENCRYPT_HOST=exam-all.duckdns.org
      - LETSENCRYPT_EMAIL=jwg8910@naver.com
      - HTTPS_METHOD=redirect   # ← 이 줄 꼭 추가!
    ports:
      - "3000:80"
    expose:
      - "80"
    deploy:
      resources:
        limits:
          memory: 1536M  # 1.5GB
          cpus: '1.0'

  nginx-proxy:
    image: jwilder/nginx-proxy
    container_name: nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./certs:/etc/nginx/certs
      - ./vhost.d:/etc/nginx/vhost.d
      - ./html:/usr/share/nginx/html
    networks:
      - my-exam-network
    restart: always

  nginx-letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: nginx-letsencrypt
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./certs:/etc/nginx/certs
      - ./vhost.d:/etc/nginx/vhost.d
      - ./html:/usr/share/nginx/html
    environment:
      - NGINX_PROXY_CONTAINER=nginx-proxy
      - DEFAULT_EMAIL=jwg8910@naver.com
    depends_on:
      - nginx-proxy
    networks:
      - my-exam-network
    restart: always

  # tunnel:
  #   build:
  #     context: ./TUNNEL
  #     dockerfile: Dockerfile
  #   container_name: tunnel-container
  #   networks:
  #     my-exam-network:
  #       ipv4_address: 192.168.1.60
  #   depends_on:
  #     - fn
  #   restart: unless-stopped
  #   volumes:
  #     - ./TUNNEL/config.yml:/etc/cloudflared/config.yml
  #     - ./TUNNEL/credentials.json:/etc/cloudflared/credentials.json
  #   deploy:
  #     resources:
  #       limits:
  #         memory: 256M
  #         cpus: '0.25'

  # quicktunnel:
  #   build:
  #     context: ./QUICKTUNNEL
  #     dockerfile: Dockerfile
  #   container_name: quicktunnel-container
  #   networks:
  #     my-exam-network:
  #       ipv4_address: 192.168.1.70
  #   depends_on:
  #     - fn
  #   restart: unless-stopped
  #   deploy:
  #     resources:
  #       limits:
  #         memory: 256M
  #         cpus: '0.25'



volumes:
  nginx_upload_cache:
    driver: local